[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --log-format {s} --chip STM32G030C8Tx --protocol swd"

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
